Repository Squad-61/ReCreio_WebSite, pull requests merged in 2022-07, with the labels that each got.

#4 fet: navbar, homepage completo
  .editorconfig
  index.html
  public/assets/RECREIO.png
  public/assets/cadastro.png
  public/assets/navbar.png
  public/assets/navbar2.png
  public/css/signin.css
  public/home.html
  public/pages/cadastro.html
  stylecss.css
Labels: enhancement, good first issue

#5 feat: Jogo da Forca e Pagina de Jogos v1.0.0
  .editorconfig
  .gitignore
  public/assets/images/Jogo_da_Forca_Ilustração.png
  public/assets/images/Jogo_das_Palavras_Embaralhadas Ilustração.png
  public/assets/images/RECREIO.png
  public/assets/images/buttons/clickButton-black.png
  public/assets/images/buttons/clickButton-white.png
  public/assets/images/buttons/reload.png
  public/assets/images/cadastro.png
  public/assets/images/stickman/gallows-trace.png
  public/assets/images/stickman/gallows.png
  public/assets/images/stickman/hangmangame-arm-left.png
  public/assets/images/stickman/hangmangame-arm-right.png
  public/assets/images/stickman/hangmangame-body.png
  public/assets/images/stickman/hangmangame-head.png
  public/assets/images/stickman/hangmangame-leg-left.png
  public/assets/images/stickman/hangmangame-leg-right.png
  public/assets/images/stickman/hangmangame-stickman.png
  public/assets/videos/guia_cadastro.mp4
  public/css/games/gallows.css
  public/css/games/main.css
  public/css/games/page-landing.css
  public/css/games/pop-up.css
  public/css/main.css
  public/javascript/jogoDaForca.js
  public/pages/games/forca.html
  public/pages/games/index.html
Labels: enhancement

#6 PR para Discussão:
  README.md
Labels: documentation

#12 📃: Documentação do Repositório
  .github/.gitkeep
  .github/brand.png
  .github/logo.jpeg
  README.md
Labels: documentation, help wanted
